### ISSUE TITLE
Links to examples on multiple subsystem pages are broken

### ISSUE THREAD

**Issue by berkoben** [faucetsdn/udmi#139]
To reproduce: 
1. go to the subsystem section on the main docs page
2. click on a subsystem (ex "system")
3. click on the links on the resulting page.

Expected behavior: you get an example json
Actual behavior: you get a 404

It appears the examples on multiple subsystem pages are broken as if a directory has been moved.

**Comment by noursaidi** [comment]
The directory for the examples has moved from ~/schema to ~/tests. I'll make a change and check all links for any broken links and create a PR
