### ISSUE TITLE
wsl error running registrar "command not found"

### ISSUE THREAD

**Issue by josephedwardchang** [faucetsdn/udmi#188]
Hi all, I have windows 10 home and would like to run udmi tools under wsl (windows subsystem for linux). i have installed everything this way:

- install windows subsystem for linux: ubuntu
	get it in ms store by searching ubuntu and install it
	when installing it will prompt for new admin/password use linuxadmin/testpw
	
- once installed open ubuntu (from start menu) and run the ff:
	- explorer.exe . 
	*** this will open an explorer window where you can transfer the site_model files and the udmi tools into linux ubuntu
		- copy the essential.json, udmi tools and site model folders into your linux subsystem
	
	- sudo apt update
	- sudo apt upgrade
	- add new file gcp.sh in /etc/profile.d folder
		*** Files with the .sh extension in the /etc/profile.d directory get executed whenever a bash login shell is entered (e.g. when logging in from the console or over ssh), as well as by the DisplayManager when the desktop session loads and run this:
	
		  sudo nano /etc/profile.d
		
		You can, for instance, create the file /etc/profile.d/gcp.sh whose content is:
	
		  export GOOGLE_APPLICATION_CREDENTIALS=essential.json
		  export PATH=$PATH:~/udmi/bin
		
		save the file (ctrl-O) and copy essential.json to home dir
	- install and verify: jdk, npm, node.js, coreutils, jq
		sudo apt install default-jre
		java –version
		sudo apt install nodejs npm
		nodejs --version && npm --version
		sudo apt-get install coreutils 
		sudo dpkg-query -l | grep coreutils *
		sudo apt install jq
		curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.[0]'

*all the jdk, npm,node.js,coreutils,jq are verified working
*my udmi tools directory is in Home/udmi
*my site model is in Home/ITPE5_model 
*in commandline i am currently in Home folder 

so that i can now *theoretically* run udmi tools but registrar gives me error

    $ sudo udmi/bin/registrar ITPE5_model
    sudo: udmi/bin/registrar: command not found
    $ ls udmi/bin/registrar
    udmi/bin/registrar
    $

as you can see ls is finding registrar correctly. can anyone help? maybe i am missing something?

as i dig deeper, i could not see any binaries, is this correct? there is java src but no make file or proj file nor any doc on how to build it. any help is appreciated, thanks for any info. newbie here sorry.

**Comment by grafnu** [comment]
(moving to udmi-diacuss@)

Can you try without sudu? That's not necessary for any of the tools and it
likely has a restricted path that might be causing problems.

What about just "bash"?

I'm not familiar with WSL at all, just going on basic Linux debugging...

**Comment by josephedwardchang** [comment]
$ udmi/bin/registrar ITPE5_model
-bash: udmi/bin/registrar: Permission denied
$ ls ITPE5_model
README.md  cloud_iot_config.json  devices  registration_summary.json
$ ls udmi/bin/
gencode       gencode_python  gendocs.py  keygen  provision  registrar  setup_site  test_registrar  test_sequences
gencode_java  gendocs

hmm strange that i'm getting permission denied if sudo isn't necessary...can I ask where the *.java files are? or the binaries are? all i see in the bin folders are script files and doesn't seem to call any actual java programs or that i don't see these java programs at all. Like if you take a look at bin/registrar and open it in notepad++, it's actually a just bash script..looking at these scripts i see it is using Gradle but haven't installed it yet. let me try that one.
I'm using bash, it is default for ubuntu 20.4. WSL is NOT like virtual machine, Linux is run directly within Windows. It's like having Linux run side by side with Windows

**Comment by grafnu** [comment]
The src files are validator/src but I doubt that's your problem (that would
not be permission denied). This would be the most instructive output:

~/udmi$ bash -ex bin/registrar
++ dirname bin/registrar
+ ROOT_DIR=bin/..
+ '[' 0 == 0 ']'
+ echo bin/registrar SITE_PATH '[PROJECT_ID]' '[devices...]'
bin/registrar SITE_PATH [PROJECT_ID] [devices...]
+ false

**Comment by grafnu** [comment]
The obvious thing to try are the permissions of the file itself:

~/udmi$ ls -l bin/registrar
-rwxr-xr-x 1 peringknife primarygroup 488 Aug 14 22:20 bin/registrar

Also, then run it with the "bash -ex" prefix of what command line you
normally would use:

$ bash -ex udmi/bin/registrar ITPE5_model

**Comment by josephedwardchang** [comment]
`admin@machine:~/udmi$  ls -l bin/registrar
-rw-r--r-- 1 root root 488 Sep  9 22:22 bin/registrar
admin@machine:~/udmi$ bash -ex bin/registrar ~/ITPE5_model
++ dirname bin/registrar
+ ROOT_DIR=bin/..
+ '[' 1 == 0 ']'
+ site_path=/home/linuxadmin/ITPE5_model
+ shift
+ project_id=
+ shift
+ true
+ '[' '!' -f /home/linuxadmin/ITPE5_model/cloud_iot_config.json ']'
+ echo Building validator...
Building validator...
+ bin/../validator/bin/build
bin/registrar: line 21: bin/../validator/bin/build: Permission denied`

it is interesting to note that root chowns it...let me adjust the tree permissions and then run it again. The paths thought are correct.

**Comment by grafnu** [comment]
So, it looks like something got messed up when you copied the files over.
LIkely this had to do with your "use windows to copy files" -- Windows
doesn't have the same execution permissions setup that Linux does, so if
the files ever touch a Windows FS they will lose the necessary
permissions.  I'd recommend checking out the files in the WSL bit directly
using git, and avoiding Windows altogether.  You could try fixing it
one-at-a-time but that would be a nasty game of whack-a-mole. You might be
able to do a "git reset --hard" in that directory if it copied the .git
files over as well...

**Comment by josephedwardchang** [comment]
I see. wow. thanks. yeah i'll do that now
