### ISSUE TITLE
Validator output not including field responsible for error (version)

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#283]
The following `event_pointset` payload
```
{
  "points" : {
    "crac_demand_status" : {
      "present_value" : false
    },
    "crac_temperature_setpoint" : {
      "present_value" : 25
    }
  },
  "timestamp" : "2022-03-30T15:24:27.806Z",
  "version" : 1
}
```

Produces the following output in the output
```
While converting to json node: 1 schema violations found
  1 schema violations found
    instance type (integer) does not match any allowed primitive type (allowed: ["string"])
```

I think this output should describe the field (`version`), so that if we create an exception to prevent ignore  integer version `1`, it doesn't inadvertently capture other errors because the error message is not specific.

**Comment by grafnu** [comment]
How is this being generated?  Which tool is being used?

**Comment by noursaidi** [comment]
`bin/validator` with a pubs subscription

**Comment by grafnu** [comment]
https://github.com/faucetsdn/udmi/pull/286

**Comment by josephedwardchang** [comment]
```
While converting to json node: 1 schema violations found
  1 schema violations found
    instance type (integer) does not match any allowed primitive type (allowed: ["string"])
```

I searched for this error here, and while it is indeed missing "version" as the originator of the "instance type (integer) does not match...". It actually doesn't seem to be an actual error.

I tested sending version as string: "1" but it keeps being rejected by pubsub (there is no message coming into it). 
I tested sending with version as int: 1, it gets into the pubsub correectly but validation says error as shown above "instance type (integer) does not match..."

so...which one is correct? version as string or int? maybe I have error in my settings? I have also changed my udmi schema to either version as int and version as string...but still the same error as I tested.

**Comment by grafnu** [comment]
This is currently being addressed with
https://github.com/faucetsdn/udmi/pull/286 -- should be fixed in a day or
so once I can get the PR cleaned up and submitted. There's a new "upgrade
message" feature that should address this problem, but it wasn't fully
implemented correctly the first time (I missed the relevant code path in
the validator).

The old way of doing it was an integer (1) -- but that will be deprecated
in the future, but the message upgrader feature should automatically fix
that.

The new way of doing it is a string, which should ultimately have a full
version like "1.3.14"

**Comment by josephedwardchang** [comment]
Thanks for the info sir. I'll adjust version on my side now.

**Comment by grafnu** [comment]
Ok, I just submitted the PR that I believe should fix this problem.
Basically it takes any version specification (number or string) and
automatically upgrades the message it's validating to accommodate any
changes to the "latest" version. If you still run into problems then let me
know and we can figure out how to debug more. (Make sure you pull the
latest down for the tool, and update the cloud functions if you're using
them.)

**Comment by grafnu** [comment]
Thanks -- I can confirm I can reproduce it.  Tracking internally as
b/227464335
