### ISSUE TITLE
Old firmware/make_model fields not upgraded in validator?

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#285]
Running validator using `bin/validator ~/site-model project subscription`

I have the following payload in `state_system.json`

```
{
  "firmware" : {
    "version" : "V3.0b53"
  },
  "make_model" : "EasyIO FS32",
  "operational" : true
}
```

And the following output `state_system.out`

```
While converting to json node: 2 schema violations found
  2 schema violations found
    object has missing required properties (["hardware","last_config","serial_no","software"])
    object instance has properties which are not allowed by the schema: ["firmware","make_model"]
```

The device was to an older schema, therefore has `make_model` and `firmware` in lieu of `hardware` and `software` respectively. 

My understanding was these fields should have been _upgraded_ so that these don't appear as validation errors?

**Comment by grafnu** [comment]
This is the same underlying issue as https://github.com/faucetsdn/udmi/issues/283

**Comment by grafnu** [comment]
Should be fixed by https://github.com/faucetsdn/udmi/pull/286

**Comment by grafnu** [comment]
Ok, marking as fixed. If there's further problems feel free to open a new issue (or re-open this one if it's the same).
