### ISSUE TITLE
UDMS-REFLECT cannot be in a different region to the site registries 

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#290]
We have an IoT Core setup where we have registries in different regions, e.g:
SITE_1 - us-central1
SITE_2 - europe-west1
UDMS-REFLECT - us-central1

When using the validator with the reflector (`bin/validate <site model> <project id>`) - the validator will try to connect to the UDMS-REFLECT in the same region as the the registry.

For example, if my site model is SITE_2 in europe-west1, the validator will try to connect to 
`projects/PROJECT_ID/locations/europe-west1/registries/UDMS-REFLECT/devices/SITE_2`

This fails because UDMS-REFLECT is in a different region

**Comment by grafnu** [comment]
Bad Trevor?  This feature is already there (as of a few weeks ago)... I needed it for some other work I was doing -- I just never told anybody about it!  There's even [some documentation for it](https://faucetsdn.github.io/udmi/docs/specs/site_model.html#cloud_iot_configjson)!
