### ISSUE TITLE
Pubber - large delay between message publish

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#326]
There is a 15 minute delay between message publish on pubber. 

```
INFO daq.pubber.Pubber - 2022-05-10T08:05:05Z 2022-05-10T08:05:05Z sending test message #0
INFO daq.pubber.Pubber - 2022-05-10T08:21:45Z 2022-05-10T08:21:45Z sending test message #100
```

**Comment by grafnu** [comment]
It's sending 100 messages in 15 minutes (notice the "#100") -- it's just
not logging them all b/c that makes the log output too noisy.  I believe
(but maybe my math is bad), it should be about 10s per actual event message.

**Comment by noursaidi** [comment]
You're right - it's 10 seconds between publishing. I was looking in the wrong place for some messages and attributed the fact I wasn't seeing them to those messages
