### ISSUE TITLE
Validator - missing errors in output and misleading report

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#367]
The validation output files do not all capture metadata validation errors (missing/extra points). Additionally, the overall validation report can be misleading, with some errors being truncated. This issue captures these errors and suggests how to enhance the report to not be misleading.

To replicate, use pubber
`bin/pubber sites/udmi_site_model PROJECT_ID AHU-1 123 missingPoint=filter_alarm_pressure_status extraField=extraField extraPoint=1extra.point noHardware`

## Output Files Issues

**event_pointset.out**
```
While converting to json node: 2 schema violations found
  2 schema violations found
    object instance has properties which are not allowed by the schema: [`1extra.point"]
    object instance has properties which are not allowed by the schema: ["extraField"]
Unrecognized field "extraField" (class udmi.schema.PointsetEvent), not marked as ignorable (4 known properties: "version", "points", "timestamp", "partial_update"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: udmi.schema.PointsetEvent["extraField"])
  Unrecognized field "extraField" (class udmi.schema.PointsetEvent), not marked as ignorable (4 known properties: "version", "points", "timestamp", "partial_update"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: udmi.schema.PointsetEvent["extraField"])
```
Missing:
- `Metadata validation failed: Extra points: 1extra.point`
- `Metadata validation failed: Missing points: filter_alarm_pressure_status`
- Reason for why `1extra.point` is an issue besides it being an extra point is not given (does not conform to regex)

**state_pointset.out**
```
While converting to json node: 1 schema violations found
  1 schema violations found
    object instance has properties which are not allowed by the schema: ["1extra.point"]
Metadata validation failed: Extra points: 1extra.point
```

Missing:
- `Metadata validation failed: Missing points: filter_alarm_pressure_status`
- Reason for why `1extra.point` is an issue besides it being an extra point is not given (does not conform to regex)

**state.out**
```
While converting to json node: 2 schema violations found
  2 schema violations found
    object has missing required properties (["hardware"])
    object instance has properties which are not allowed by the schema: ["1extra.point"]
```

Missing:
- `Metadata validation failed: Extra points: 1extra.point`
- `Metadata validation failed: Missing points: filter_alarm_pressure_status`
- Reason for why `1extra.point` is an issue besides it being an extra point is not given (does not conform to regex)

## Validation Report Issues

```json
{
  "updated" : "2022-06-20T12:35:41Z",
  "expectedDevices" : [ "AHU-1", "AHU-22", "GAT-123", "SNS-4" ],
  "missingDevices" : [ "AHU-22", "GAT-123", "SNS-4" ],
  "extraDevices" : [ ],
  "pointsetDevices" : [ ],
  "base64Devices" : [ ],
  "errorDevices" : {
    "AHU-1" : {
      "errors" : [ "java.lang.RuntimeException: While converting to json node: 2 schema violations found", "java.lang.IllegalArgumentException: Unrecognized field \"extraField\" (class udmi.schema.PointsetEvent), not marked as ignorable (4 known properties: \"version\", \"points\", \"timestamp\", \"partial_update\"])\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: udmi.schema.PointsetEvent[\"extraField\"])", "java.lang.RuntimeException: While converting to json node: 1 schema violations found", "java.lang.RuntimeException: Metadata validation failed: Extra points: 1extra.point", "java.lang.RuntimeException: While converting to json node: 2 schema violations found", "java.lang.RuntimeException: While converting to json node: 1 schema violations found" ],
      "extraPoints" : [ "1extra.point" ],
      "missingPoints" : [ "filter_alarm_pressure_status" ]
    }
  }
}
```

The errors `java.lang.RuntimeException: While converting to json node: 2 schema violations found` and `java.lang.RuntimeException: While converting to json node: 1 schema violations found` which presumably come from `state` and one of `state_pointset` or `state_system` are missing the actual error, and the report needs to be updated to include these. There may be possible duplication of errors because it seems to be from the overall state validation as well as one of the sub block validations.

The `java.lang.RuntimeException` at the start of each error should be removed

The metadata missing/extra point errors e.g. `java.lang.RuntimeException: Metadata validation failed: Extra points: 1extra.point",` could also be removed as there is a dedicated extraPoints and missingPoints fields.

The message the error belongs too should also be appended. e.g. `Error validating event_pointset ...`

## Validation Report Categories Enhancement

At the moment devices are classified into the following categories:
- `expectedDevices` 
- `missingDevices` 
- `extraDevices` 
- `pointsetDevices` (which I think currently misleadingly means devices with no errors)
- `base64Devices` 
- `errorDevices` 

I'd like to suggest the following categories:
- `cleanDevices` - devices with no validation errors
- `pointsetEventDevices` - devices which publish pointset
- `cleanPointsetEventDevices` - devices which publish pointset events and no validation errors
- `systemEventDevices` - devices which publish system events
- `cleanSystemEventDevices` - devices which publish system events and no validation errors
- `stateDevices` - devices which send state
- `cleanStateDevices` - devices which send state and no validation errors

**Comment by grafnu** [comment]
It seems like this is ~3 different issues?  It would really help to break them out and keep them separate.

**Comment by noursaidi** [comment]
Broken out into #371 #372 #373
