### ISSUE TITLE
validation_report.json truncated errors

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#372]
The `validation_report.json` file truncates some errors when listed in the errors field. 

To replicate, use pubber
`bin/pubber sites/udmi_site_model PROJECT_ID AHU-1 123 missingPoint=filter_alarm_pressure_status extraField=extraField extraPoint=1extra.point noHardware` using the site model example (`bin/clone_model`)

validation_report.json:
```json
{
  "updated" : "2022-06-20T12:35:41Z",
  "expectedDevices" : [ "AHU-1", "AHU-22", "GAT-123", "SNS-4" ],
  "missingDevices" : [ "AHU-22", "GAT-123", "SNS-4" ],
  "extraDevices" : [ ],
  "pointsetDevices" : [ ],
  "base64Devices" : [ ],
  "errorDevices" : {
    "AHU-1" : {
      "errors" : [ "java.lang.RuntimeException: While converting to json node: 2 schema violations found", "java.lang.IllegalArgumentException: Unrecognized field \"extraField\" (class udmi.schema.PointsetEvent), not marked as ignorable (4 known properties: \"version\", \"points\", \"timestamp\", \"partial_update\"])\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: udmi.schema.PointsetEvent[\"extraField\"])", "java.lang.RuntimeException: While converting to json node: 1 schema violations found", "java.lang.RuntimeException: Metadata validation failed: Extra points: 1extra.point", "java.lang.RuntimeException: While converting to json node: 2 schema violations found", "java.lang.RuntimeException: While converting to json node: 1 schema violations found" ],
      "extraPoints" : [ "1extra.point" ],
      "missingPoints" : [ "filter_alarm_pressure_status" ]
    }
  }
}
```

The errors `java.lang.RuntimeException: While converting to json node: 2 schema violations found` and `java.lang.RuntimeException: While converting to json node: 1 schema violations found` which presumably come from `state` and one of `state_pointset` or `state_system` are missing the actual error. The  report needs to be updated to include these. 

There may be possible duplication of errors because it seems to be from the overall state validation as well as one of the sub block validations.

**Comment by grafnu** [comment]
I don't actually think trying to capture the entire error in the validation_report.json file is the right way to go, rather, it might just say "validation errors" and then you have to go look at the other file to get the actual errors.  Complete error reports can get messy, and trying to include it all in the validation_report.json file just makes that file a big mess.  This kinda happens already, it's just that there's a partial attempt to have "useful" information in the summary report itself, which is a half-way solution that seems more confusing than it's worth. Thoughts?

**Comment by noursaidi** [comment]
I do agree that complete error reports get messy (and manually reading a JSON file is very very messy indeed), but in the absence of a better way to view the results, having all the information in a single report is better. This is because you can scroll down and see the errors without having to click into two or three files for each device to see what the errors errors, it can be searched (CTRL+F) and is a single file snapshot of validation which can be shared, stored, etc.

From my experience there tends to be only a few unique errors that are exhibited by a large numbers of devices. One example is an entire site where the errors are not having `version` or `last_update` in state messages, and that's the only error. Very easy to see that by scrolling through the report.

I guess it's less _report_ and more _database_
