### ISSUE TITLE
Pubber - build/libs/pubber-1.0-SNAPSHOT-all.jar: No such file or directory

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#398]
Yesterday and today on my Mac and Ubuntu 22.04 machines, I've started encountering this issue recently which prevents pubber building.

My fix was to clone a new copy of the UDMI repo, and then running pubber from the new copy. This works.

Git clean & reset in the original directory do not resolve the issue. But running `./gradlew assemble` does create `build/libs/pubber-1.0-SNAPSHOT-all.jar: ` 

```
% pubber/bin/build
Building pubber in /Users/nournew/udmi7/udmi/pubber

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

BUILD SUCCESSFUL in 2s
2 actionable tasks: 1 executed, 1 up-to-date
ls: build/libs/pubber-1.0-SNAPSHOT-all.jar: No such file or directory
```

**Comment by grafnu** [comment]
I think it might be something with the build cache -- e.g. removing "udmi/.gradle" might fix it...

**Comment by noursaidi** [comment]
I confirm, removing the directory `pubber/.gradle` fixed this for me. Thanks!
