### ISSUE TITLE
Validator - state validation report named  "state_update.out"

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#405]
Validator outputs a file named `state_update.out`, presumably this corresponds to the "state.json" message, however there are results for `state_pointset.out` and `state_system.out`

```
nournew@macbook-2 udmi % ls -1 sites/udmi_site_model/out/devices/AHU-1 | grep state
state.attr
state.json
state_pointset.attr
state_pointset.json
state_pointset.out
state_system.attr
state_system.json
state_system.out
state_update.out
```

Contents of `state_update.out`
```
{
  "timestamp" : "2022-08-03T11:22:29Z",
  "version" : "1.3.14",
  "sub_folder" : "update",
  "sub_type" : "state",
  "status" : {
    "message" : "While converting to json node: 1 schema violations found",
    "category" : "validation.error.simple",
    "level" : 500
  }
}
```

**Comment by grafnu** [comment]
@noursaidi Was this one fixed along with the others, or is it still pending?

**Comment by noursaidi** [comment]
`state_update` is gone, but `state.json` and `state.attr` still exist

I recall that when messages are upgraded, `state.json` was the original un-upgraded message, and `state_system.json` was the upgraded, so I just need to do some investigation there and determine what the right behaviour is with representing the results from upgraded messages. 


```
nournew@macbook-2 udmi % ls sites/udmi_site_model/out/devices/AHU-1
event_pointset.attr	event_system.json	state.json		state_system.attr
event_pointset.json	event_system.out	state_pointset.attr	state_system.json
event_system.attr	state.attr		state_pointset.json
```
