### ISSUE TITLE
Units alignment between DBO and UDMI

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/udmi#46]
Should the [list of units in the UDMI repo](https://github.com/faucetsdn/udmi/blob/master/schema/units.json) be aligned with the [list of units in the DBO repo](https://github.com/google/digitalbuildings/blob/master/ontology/yaml/resources/units/units.yaml)?

**Comment by jhughesbiot** [comment]
What are the valid units now?  The units file has been deleted from the repo and the DBO is a much smaller subset of what the units file contained. There also appears to be no definition of what a Null unit is in that file but there was in the old units.json file.

**Comment by grafnu** [comment]
UDMI no longer cares about units, so it has no opinion about "valid units" -- it only matters now in relationship to DBO, so if that subset is not sufficient then it should be raised there.
