### ISSUE TITLE
While converting message to udmi.schema.Metadata, Cannot construct instance of `udmi.schema.Metadata

### ISSUE THREAD

**Issue by Karthi8883** [faucetsdn/udmi#485]
While  running registrar tool, getting this error and unable to update device data , below error while running registrar

Working with project XXxXXXXX registry xxxxxx/xxxxxxxx
Loading local device DDC-10
Warning: Nashorn engine is planned to be removed from a future JDK release
Finished loading 1 local devices.
Deleting (invalid) /mnt/c/Users/xxxxxxx/AppData/Local/Google/Cloud SDK/./xxxxxxx/UDMI/devices/DDC-10/out/metadata_norm.json
Retrieved 500 devices from registry...
Retrieved 1000 devices from registry...
Retrieved 1500 devices from registry...
Retrieved 1844 devices from registry...
Fetched 1844 devices from cloud registry xxxxxxxx
**Skipping (invalid) DDC-10**
Finished processing 1 device records...
Updated 0 devices (out of 1)
Skipped 0 not-in-cloud devices.
Updating ./xxxxxxxx/UDMI/devices/DDC-10/out/errors.json

---------------------------------------------------------
Below error for your reference, kindly suggest to solve this issue

Exceptions for AHU-1
  While loading credentials for local device AHU-1
    **java.lang.NullPointerException
  While converting message to udmi.schema.Metadata
    Cannot construct instance of `udmi.schema.Metadata` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{**
  "version" : "1.3.14",
  "timestamp" : "2020-12-08T09:03:43Z",
  "system" : {
    "location" : {
      "site_name" : "XXXXXXXX",
      "section" : "XXXXXXXXXX",
      "position" : {
        "x" : "10",
        "y" : "10",
        "z" : "10"
      }
    },
    "physical_tag" : {
      "asset" : {
        "guid" : "uuid://XXXXXXXXXXXXXXXXXXX",
        "site" : "XXXXXXXXXX",
        "name" : "AHU-1"
      }
    }
  },
  "pointset" : {
    "points" : {
      "ahu_1_chilled_supply_water_temperature_sensor" : {
        "units" : "degrees_celsius"
      },
      "ahu_1_chilled_water_valve_percentage_command" : {
        "units" : "percent"
      },
      "ahu_1_chilled_water_valve_percentage_sensor" : {
        "units" : "percent"
      },
      "ahu_1_exhaust_fan_run_command" : {
        "units" : ""
      },
      "ahu_1_exhaust_fan_run_mode" : {
        "units" : ""
      },
      "ahu_1_exhaust_fan_run_status" : {
        "units" : ""
      },
      "ahu_1_exhaust_fan_speed_percentage_command" : {
        "units" : "percent"
      },
      "ahu_1_exhaust_fan_speed_percentage_sensor" : {
        "units" : "percent"
      },
      "ahu_1_filter_differential_pressure_sensor_1" : {
        "units" : "pascals"
      },
      "ahu_1_filter_differential_pressure_sensor_2" : {
        "units" : "pascals"
      },
      "ahu_1_outside_air_damper_percentage_command" : {
        "units" : "percent"
      },
      "ahu_1_outside_air_flowrate_sensor" : {
        "units" : "cubic_feet_per_minute"
      },
      "ahu_1_outside_air_flowrate_setpoint" : {
        "units" : "cubic_feet_per_minute"
      },
      "ahu_1_return_air_co2_concentration_sensor" : {
        "units" : "parts_per_million"
      },
      "ahu_1_return_air_co2_concentration_setpoint" : {
        "units" : "parts_per_million"
      },
      "ahu_1_return_air_relative_humidity_sensor" : {
        "units" : "percent_relative_humidity"
      },
      "ahu_1_return_air_temperature_sensor" : {
        "units" : "degrees_celsius"
      },
      "ahu_1_supply_air_relative_humidity_sensor" : {
        "units" : "percent_relative_humidity"
      },
      "ahu_1_supply_air_static_pressure_sensor_1" : {
        "units" : "pascals"
      },
      "ahu_1_supply_air_static_pressure_sensor_2" : {
        "units" : "pascals"
      },
      "ahu_1_supply_air_static_pressure_setpoint" : {
        "units" : "pascals"
      },
      "ahu_1_supply_air_static_pressure_setpoint_2" : {
        "units" : "pascals"
      },
      "ahu_1_supply_air_temperature_sensor" : {
        "units" : "degrees_celsius"
      },
      "ahu_1_supply_air_temperature_setpoint" : {
        "units" : "degrees_celsius"
      },
      "ahu_1_supply_fan_failed_alarm" : {
        "units" : ""
      },
      "ahu_1_supply_fan_run_command" : {
        "units" : ""
      },
      "ahu_1_supply_fan_run_mode" : {
        "units" : ""
      },
      "ahu_1_supply_fan_run_status" : {
        "units" : ""
      },
      "ahu_1_supply_fan_speed_frequency_sensor" : {
        "units" : "hertz"
      },
      "ahu_1_supply_fan_speed_mode" : {
        "units" : ""
      },
      "ahu_1_supply_fan_speed_percentage_command" : {
        "units" : "percent"
      },
      "ahu_1_zone_air_co2_concentration_sensor_1" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_co2_concentration_sensor_2" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_co2_concentration_sensor_3" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_co2_concentration_sensor_4" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_co2_concentration_sensor_5" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_co2_concentration_sensor_6" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_pm10pt0_concentration_sensor" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_pm2pt5_concentration_sensor" : {
        "units" : "parts_per_million"
      },
      "ahu_1_zone_air_voc_concentration_sensor" : {
        "units" : "parts_per_million"
      },
      "ahu_10_chilled_supply_water_temperature_sensor" : {
        "units" : "degrees_celsius"
      }
    }
  },
  "gateway" : {
    "gateway_id" : "DDC-3"
  }
}')
 **at [Source: (String)""{\n  \"version\" : \"1.3.14\",\n  \"timestamp\" : \"2020-12-08T09:03:43Z\",\n  \"system\" : {\n    \"location\" : {\n      \"site_name\" : \"XXXXXXX\",\n      \"section\" : \"XXXXXXXX\",\n      \"position\" : {\n        \"x\" : \"10\",\n        \"y\" : \"10\",\n        \"z\" : \"10\"\n      }\n    },\n    \"physical_tag\" : {\n      \"asset\" : {\n        \"guid\" : \"uuid://XXXXXXXXXXXX\",\n        \"site\" : \"IXXXXXXX\",\n        \"name\" : \"AHU-1\"\n  "[truncated 4271 chars]; line: 1, column: 1]
  java.lang.NullPointerException**

**Comment by noursaidi** [comment]
Hi @Karthi8883 thanks for reporting this bug, this has now been fixed in #486
