### ISSUE TITLE
VALIDATOR-ERROR-FOR-STATE-PAYLOAD

### ISSUE THREAD

**Issue by darshanjain12** [faucetsdn/udmi#564]
Hi Team,

Raising this issue to cross check that the payload i am sending from controller is as per the udmi schema as i am getting an error. As i tried but couldn't find difference.

Would be great help if some could help what's wrong or some change is required.

**Payload Sent from the controller:**

{
  "timestamp": "2023-01-23T15:39:02.000Z",
  "version": "1",
  "system": {
    "last_config": "2022-12-05T09:03:43Z",
    "serial_no": "40412240",
    "hardware": {
      "make": "EasyIO",
      "sku": "PLACEHOLDER",
      "rev": "PLACEHOLDER",
      "model": "FW-04"
    },
    "software": {
      "firmware": "V1.0b21f_GS"
    },
    "operation": {
      "operational": true
    }
  }
}

**Error we getting when running a udmi validator:**

{
  "timestamp" : "2023-01-23T16:09:05Z",
  "version" : "1.4.0",
  "sub_folder" : "update",
  "sub_type" : "state",
  "status" : {
    "message" : "operation key in older version",
    "detail" : "state_update: operation key in older version @Validator.upgradeMessage(Validator.java:908)",
    "category" : "validation.device.schema",
    "timestamp" : "2023-01-23T16:09:05Z",
    "level" : 500
  },
  "errors" : [ {
    "message" : "operation key in older version",
    "detail" : "state_update: operation key in older version @Validator.upgradeMessage(Validator.java:908)",
    "category" : "validation.device.schema",
    "timestamp" : "2023-01-23T16:09:05Z",
    "level" : 500
  } ]
}

**Comment by darshanjain12** [comment]
Hi @noursaidi  Thanks for the reply.
The first solution did work out well. I changed the version in state payload to 1.4.1 and there were no longer errors.
The second solution also i tried but the second solution didnt remove the error. I started to get this error.

State Payload sent from the controller:
{
  "timestamp": "2023-01-23T18:42:50.000Z",
  "version": "1",
  "system": {
    "last_config": "2022-12-05T09:03:43Z",
    "serial_no": "40412242",
    "operational": true,
    "hardware": {
      "make": "EasyIO",
      "model": "FS32",
      "sku": "PLACEHOLDER",
      "rev": "PLACEHOLDER"
    },
    "software": {
      "firmware": "V3.0b53"
    }
  }
}

Error got on validator:

  "errors" : [ {
    "message" : "While converting to json node: 2 schema violations found",
    "detail" : "state_system: While converting to json node: 2 schema violations found @Validator.validateMessage(Validator.java:454); 2 schema violations found; object instance has properties which are not allowed by the schema: [\"operational\"]; object has missing required properties ([\"operation\"])",
    "category" : "validation.device.schema",
    "timestamp" : "2023-01-23T18:44:38Z",
    "level" : 500
  } ]
}

**Comment by darshanjain12** [comment]
Please suggest what can be done if previous versions have to be used

**Comment by grafnu** [comment]
From what I can tell, the latest version does work with the "upgrade from
version 1" case -- I just tried it with your specific test example. If you
find this to not be the case then let me know and I can addressit.  But, in
general if previous versions have to be used then the system should
compensate.
