### ISSUE TITLE
EVENTS_POINTSET DATA NOT AVAILABLE WITH VALIDATOR FOR VALIDATION

### ISSUE THREAD

**Issue by darshanjain12** [faucetsdn/udmi#614]
Hi Team I just update my local repo & after that i did try to run the validator few points wanted help on.

1. Started giving some errors under state_system.out specifically  " operation key is of older version".
2. Didnot find any events_pointset.json files in the validator out folder.

Would appreciate your help.

**Comment by noursaidi** [comment]
Hi @darshanjain12 

The first error you referred to is a bug which has now been fixed 

Can you give more details about the event_pointset issue? Do you have logs you can share?

**Comment by grafnu** [comment]
The fundamental problem with the "did not find any" situation is that it's
very hard to debug!  There *should* be an output file for every type of
message received, but if not received then correct, it would be missing.
If this issue persists (no output file) and you're confident that a message
is being sent then we'd likely need to do some more triage.  E.g., with the
adequate access to your project (e.g. a subscription on the topic) then I
can run the tools locally on *your* device and *your *project so I'm
looking at the same data stream you are!  Technically it's relatively easy,
just needs a bit of coordination.  Let me know if you continue to have this
problem (no event message showing up) and we can go from there.

**Comment by darshanjain12** [comment]
Hi @grafnu  @noursaidi 

Thank you for the response .

Yes I am still facing the same problem.

I used to the get  list of  files attached in the snapshot 1 before making a git pull, after updating the repo recently the event_pointset.json file went missing, snap for the same has been attached in snap2. 
We need that file to actually validate the telemetry data as per the metadata .

Also we have been seeing the pointsets previously before the update so that makes me confirm that the controllers are sending the telemetry data.
Also we can see the same
![snaptelemetry111](https://user-images.githubusercontent.com/104188629/223942193-300197f7-f63a-4c78-8047-a5a3f2a53327.png)


Would be great help if you would help me resolve this issue. Please comment if any thing required from my end,

![Screenshot from 2023-03-09 11-24-15](https://user-images.githubusercontent.com/104188629/223938476-fba5c25a-a962-4285-93b0-de85946ca0cd.png)
![Screenshot from 2023-03-09 11-39-18](https://user-images.githubusercontent.com/104188629/223938517-c71b94dc-f50e-46d7-8706-2290b61e284d.png)

**Comment by grafnu** [comment]
Can you give me access to your GCP project (and let me know what it's
called?) -- edit access should be enough.  I know kinda how to check what's
going on -- I basically want to put a tap on the topic subscription and
look at the raw messages, and that will be easiest. I want to run a trace
capture as described misc/gcloud_pubsub_mirror/README.md -- and that will
be the easiest way (or, you can try running that, figuring out where to put
the files, etc...).  Basically, I'm looking for a raw message feed before
the validator does anything so I can partition the problem (also then can
debug trace playback rather than live data).

Cheers,
  Trevor

**Comment by noursaidi** [comment]
@grafnu @darshanjain12 

I have investigated the issue. The problem here lies with the configuration of the project. I will follow up by email, and keep this issue open so that you can try again once the configuration issue of the project has been resolved

**Comment by darshanjain12** [comment]
@noursaidi  Are the changes done. Do i need to check something from my side.

**Comment by noursaidi** [comment]
@darshanjain12 i understand the changes to the project have been done,so rerunning the validator should show telemetry

**Comment by darshanjain12** [comment]
Yes its working Now!! Thanks for the help
