### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by nicklasfrahm** [faucetsdn/udmi#88]
Hi,

I have been in contact with this project as part of a collaboration with Danfoss. I am curious if you would be interested in boosting the visibility of this project by setting up a hosted website with the documentation in the `docs/` folder.

I was thinking that I could set up [MkDocs](https://www.mkdocs.org/) with [this theme](https://github.com/squidfunk/mkdocs-material).

Let me know your thoughts on this.

**Comment by pisuke** [comment]
Now done with this URL [https://faucetsdn.github.io/udmi/docs/](https://faucetsdn.github.io/udmi/docs/)
