### ISSUE TITLE
UDMI Validator Run Cloud Function error

### ISSUE THREAD

**Issue by darshanjain12** [faucetsdn/udmi#989]
Hi Team,

I was recently able to run the Validator without any issues, but now I'm encountering an error: "Waiting for initial config, Config sync timeout expired." Could someone please assist me in resolving this? Thank you!

**Comment by grafnu** [comment]
Sure, but I'd need some additional detail. Maybe start with the output of
the command until that error... something like the following (except in
this case there's no error...)

***@***.***:~/udmi$ bin/validator site_model/
//gbos/bos-platform-dev/peringknife
Cleaning /home/peringknife/udmi/validator/bin/../build/
Mirroring udmi files...
Java version openjdk 17.0.12 2024-07-16 OpenJDK Runtime Environment (build
17.0.12+7-Debian-1build1) OpenJDK 64-Bit Server VM (build
17.0.12+7-Debian-1build1, mixed mode, sharing)
Building validator in /home/peringknife/udmi/validator
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 19s
2 actionable tasks: 2 executed
-rw-r--r-- 1 peringknife primarygroup 40465521 Oct 13 08:59
build/libs/validator-1.0-SNAPSHOT-all.jar
Done with validator build.
udmi version 1.5.1-79-gfcccba51
starting run at 2024-10-13T15:59:16+00:00
java -cp
/home/peringknife/udmi/validator/build/libs/validator-1.0-SNAPSHOT-all.jar
com.google.daq.mqtt.util.Dispatcher validator site_model/
//gbos/bos-platform-dev/peringknife
Writing reconciled configuration file to
/home/peringknife/udmi/out/validator_conf.json
Generating report file in
/home/peringknife/udmi/site_model/out/validation_report.json
Loaded 4 expected devices
Loading reflector key file from
/home/peringknife/udmi/site_model/reflector/rsa_private.pkcs8
Instantiating reflector client //gbos/bos-platform-dev/peringknife~
peringknife~ZZ-TRI-FECTA
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher - Loaded key
/home/peringknife/udmi/site_model/reflector/rsa_private.pkcs8 as sha256
42a8a8f1287aa775
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher -
peringknife~ZZ-TRI-FECTA token expiration sec 3600
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher -
peringknife~ZZ-TRI-FECTA creating client
projects/bos-platform-dev/locations/us-central1/registries/peringknife~UDMI-REFLECT/devices/peringknife~ZZ-TRI-FECTA
on ssl://mqtt.bos.goog:8883
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher -
peringknife~ZZ-TRI-FECTA creating new auth token for audience
bos-platform-dev
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher - Creating jwt
RS256 key with audience bos-platform-dev
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher -
peringknife~ZZ-TRI-FECTA connecting to mqtt server ssl://mqtt.bos.goog:8883
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher - Subscribing with
qos 1 to topic /devices/peringknife~ZZ-TRI-FECTA/config
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher - Subscribing with
qos 1 to topic /devices/peringknife~ZZ-TRI-FECTA/errors
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher - Subscribing with
qos 0 to topic /devices/peringknife~ZZ-TRI-FECTA/commands/#
[main] INFO com.google.bos.iot.core.proxy.MqttPublisher -
peringknife~ZZ-TRI-FECTA done with setup connection
Subscribed to
projects/bos-platform-dev/locations/us-central1/registries/peringknife~UDMI-REFLECT/devices/peringknife~ZZ-TRI-FECTA
Starting initial UDMI setup process
Setting state version 1.5.1-79-gfcccba51 timestamp 2024-10-13T15:59:18Z
UDMI setting reflectorState: {
  "version" : "1.5.1-79-gfcccba51",
  "udmi" : {
    "setup" : {
      "user" : "peringknife",
      "transaction_id" : "RC:c959c8.0001"
    }
  },
  "timestamp" : "2024-10-13T15:59:18Z"
}
UDMI received reflectorConfig: {
  "last_state" : "2024-10-13T15:59:18Z",
  "reply" : {
    "transaction_id" : "RC:c959c8.0001"
  },
  "setup" : {
    "hostname" : "udmis-pods-859d79b6cf-mv9f5",
    "functions_min" : 15,
    "functions_max" : 15,
    "udmi_version" : "1.5.1-99-gf7feda88",
    "udmi_ref" : "ghcr.io/grafnu/udmi:udmis-gf7feda883",
    "built_at" : "2024-10-11T16:59:00Z",
    "built_by" : ***@***.***"
  }
}
UDMI matching last_state 2024-10-13T15:59:18Z against expected
2024-10-13T15:59:18Z
UDMI version mismatch: 1.5.1-79-gfcccba51
UDMI functions support versions 15:15 (required 15)
Running udmi tools version 1.5.1-79-gfcccba51
Entering message loop on
projects/bos-platform-dev/locations/us-central1/registries/peringknife~UDMI-REFLECT/devices/peringknife~ZZ-TRI-FECTA
Updating validated
/home/peringknife/udmi/site_model/out/validation_report.json
UDMI received reflectorConfig: {
  "timestamp" : "2024-10-13T15:59:20Z",
  "setup" : {
    "hostname" : "udmis-pods-859d79b6cf-p68nl",
    "functions_min" : 15,
    "functions_max" : 15,
    "udmi_version" : "1.5.1-99-gf7feda88",
    "udmi_ref" : "ghcr.io/grafnu/udmi:udmis-gf7feda883",
    "built_at" : "2024-10-11T16:59:00Z",
    "built_by" : ***@***.***"
  }
}
UDMI matching last_state null against expected 2024-10-13T15:59:18Z
UDMI ignoring mismatching timestamp null
Updating validated
/home/peringknife/udmi/site_model/out/validation_report.json

**Comment by darshanjain12** [comment]
udmi version 1.5.1-65-g0b0b15ba
starting run at 2024-10-14T05:39:50+00:00
java -cp /home/dell/udmi/validator/build/libs/validator-1.0-SNAPSHOT-all.jar com.google.daq.mqtt.util.Dispatcher validator /home/dell/XX-YYY-ZZZZZZ/udmi/cloud_iot_config.json
Writing reconciled configuration file to /home/dell/udmi/out/validator_conf.json
Generating report file in /home/dell/XX-YYY-ZZZZZZ/udmi/./out/validation_report.json
Loaded 6 expected devices
Loading reflector key file from /home/dell/XX-YYY-ZZZZZZ/udmi/./reflector/rsa_private.pkcs8
Instantiating reflector client //gtest/test-platform-test/ XX-YYY-ZZZZZZ
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - Loaded key /home/dell/XX-YYY-ZZZZZZ/udmi/./reflector/rsa_private.pkcs8 as sha256 3a35f84ed69ddf40
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - XX-YYY-ZZZZZZ token expiration sec 3600
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - XX-YYY-ZZZZZZ creating client projects/test-platform-test/locations/us-central1/registries/UDMI-REFLECT/devices/XX-YYY-ZZZZZZ on ssl://mqtt.test.goog:8883
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - XX-YYY-ZZZZZZ creating new auth token for audience test-platform-test
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - Creating jwt RS256 key with audience test-platform-test
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - XX-YYY-ZZZZZZ connecting to mqtt server ssl://mqtt.test.goog:8883
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - Subscribing with qos 1 to topic /devices/XX-YYY-ZZZZZZ/config
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - Subscribing with qos 1 to topic /devices/XX-YYY-ZZZZZZ/errors
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - Subscribing with qos 0 to topic /devices/XX-YYY-ZZZZZZ/commands/#
[main] INFO com.google.test.iot.core.proxy.MqttPublisher - XX-YYY-ZZZZZZ done with setup connection
Subscribed to projects/test-platform-test/locations/us-central1/registries/UDMI-REFLECT/devices/XX-YYY-ZZZZZZ
Starting initial UDMI setup process
Sending UDMI reflector state: {
  "version" : "1.5.1-65-g0b0b15ba",
  "udmi" : {
    "setup" : {
      "user" : "dell",
      "msg_source" : "debug",
      "tool_name" : "validator",
      "transaction_id" : "RC:95ab02.0001"
    }
  },
  "timestamp" : "2024-10-14T05:39:51Z"
}
Exception in main: Waiting for initial config, Config sync timeout expired. Investigate UDMI cloud functions install.
java.lang.RuntimeException: Waiting for initial config
        at com.google.test.iot.core.proxy.IotReflectorClient.<init>(IotReflectorClient.java:184)
        at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.java:531)
        at com.google.daq.mqtt.validator.Validator.execute(Validator.java:250)
        at com.google.daq.mqtt.validator.Validator.main(Validator.java:264)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at com.google.daq.mqtt.util.Dispatcher.main(Dispatcher.java:44)
Caused by: java.lang.RuntimeException: Config sync timeout expired. Investigate UDMI cloud functions install.
        at com.google.test.iot.core.proxy.IotReflectorClient.<init>(IotReflectorClient.java:171)
        ... 8 more

**Comment by darshanjain12** [comment]
@grafnu We have replaced the site and project specific information with some other keywords. Please let us know if more details required

**Comment by grafnu** [comment]
Or, we found the (maybe) problem -- the backend servers weren't actually
updated so they were on an unexpectedly old version. If you try again (with
HEAD like you had originally) it should (hopefully) work now.

**Comment by darshanjain12** [comment]
Yes @grafnu Its working now. Thank you so much for your prompt response
